# -*- coding: utf-8 -*-
"""3rd_class.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/124BDSTdIgE_PFzI_Ox9V_uVi4UVtgC2x

# Comerission & Logical Operators & conditions:

*   == Dubble equal to
"""

# exemple of comperision opreator == equal to:
# is code me hamny 2 variables bnae hen
# variable one me ham ny 1 passoword machine ko store krdia
# or variable two me ham user se us password k bary me poch rahe hen

# variabls:
dev_pass: str = "pass12"
user_pass: str = (input("enter your password: "))

# if statement:
# is statement/block me ham ye dekhengy k hmari statement ki condition
# same hen to if ka answer print hoga:

if dev_pass == user_pass:
  print("Welcome, You are Successfuly loged in")

# else statement:
# is statement/block me ham ye dekhengy k hmari statement ki condition
# same nhe hen to else ka answer print hoga:

else:
  print("Wrong Password! try again please.")

"""

*   Usess of Comperission  & Logical operators in Form:
"""

# exemple of diffrent comperission operators:
# exemple of diffrent comperission operators:
# ham 1 form k base pr user se inputs lengy or diffrents type
# of compression operators ko use krty huwe:

candidate: str = input("enter your name")
marks: str = input("enter your governor IT test marks")

print(candidate)

# Convert marks to an integer before comparison

if int(marks) <= 25:
   print("A+1 Grade")
   print("Well-done! You are able to Governor Onsite IT Class")